In [1]:
import pandas as pd

In [2]:
df=pd.read_csv(r"C:\Users\asus\Python class\Intership\Airport_Operations_20k_Realistic.csv")

In [3]:
df.head()

,Flight_ID,Airline,Origin,Destination,Aircraft_Type,Terminal,Gate,Weather_Condition,Flight_Date,Month,...,Passenger_Count,Load_Factor (%),Ground_Staff_Count,Baggage_Count,Fuel_Quantity_Liters,Gate_Occupancy_Min,Turnaround_Time_Min,Actual_Departure,Actual_Arrival,Delay_Reason
0,FL100000,Akasa Air,CCU,BOM,B777,T3,G9,Rain,2025-02-09 00:00:00,February,...,256,83.46,23,312,60774,53,100,2025-02-09 15:34:00,2025-02-09 17:18:00,No Delay
1,FL100001,Vistara,BOM,MAA,B777,T2,G18,Clear,2025-06-17 00:00:00,June,...,59,95.21,22,75,30079,74,100,2025-06-17 09:15:00,2025-06-17 13:38:00,No Delay
2,FL100002,Qatar Airways,MAA,CCU,B787,T1,G43,Clear,2025-04-19 00:00:00,April,...,138,65.68,16,191,27653,73,108,2025-04-19 10:26:00,2025-04-19 13:54:00,No Delay
3,FL100003,Akasa Air,HYD,DEL,B777,T2,G24,Clear,2025-10-08 00:00:00,October,...,253,83.22,22,274,67394,102,105,2025-10-08 20:29:00,2025-10-08 23:29:00,No Delay
4,FL100004,SpiceJet,BLR,CCU,A321,T1,G27,Clear,2025-02-25 00:00:00,February,...,63,94.33,8,86,63337,113,117,2025-02-25 23:21:00,2025-02-26 01:17:00,Maintenance

In [4]:
df.shape

(20000, 35)

In [5]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 20000 entries, 0 to 19999
Data columns (total 35 columns):
 #   Column                        Non-Null Count  Dtype
---  ------                        --------------  -----
 0   Flight_ID                     20000 non-null  object
 1   Airline                       20000 non-null  object
 2   Origin                        20000 non-null  object
 3   Destination                   20000 non-null  object
 4   Aircraft_Type                 20000 non-null  object
 5   Terminal                      20000 non-null  object
 6   Gate                          20000 non-null  object
 7   Weather_Condition             20000 non-null  object
 8   Flight_Date                   20000 non-null  object
 9   Month                         20000 non-null  object
 10  Scheduled_Departure           20000 non-null  object
 11  Scheduled_Arrival             20000 non-null  object
 12  Status                        20000 non-null  object
 13  Gate_Delay_Min                20000 non-null  int64
 14  Fuel_Delay_Min                20000 non-null  int64
 15  Baggage_Delay_Min             20000 non-null  int64
 16  Catering_Delay_Min            20000 non-null  int64
 17  Passenger_Transfer_Delay_Min  20000 non-null  int64
 18  Cleaning_Delay_Min            20000 non-null  int64
 19  Security_Delay_Min            20000 non-null  int64
 20  Maintenance_Delay_Min         20000 non-null  int64
 21  ATC_Delay_Min                 20000 non-null  int64
 22  Total_Delay_Min               20000 non-null  int64
 23  Departure_Delay_Min           20000 non-null  int64
 24  Arrival_Delay_Min             20000 non-null  int64
 25  Passenger_Count               20000 non-null  int64
 26  Load_Factor (%)               20000 non-null  float64
 27  Ground_Staff_Count            20000 non-null  int64
 28  Baggage_Count                 20000 non-null  int64
 29  Fuel_Quantity_Liters          20000 non-null  int64
 30  Gate_Occupancy_Min            20000 non-null  int64
 31  Turnaround_Time_Min           20000 non-null  int64
 32  Actual_Departure              19001 non-null  object
 33  Actual_Arrival                19001 non-null  object
 34  Delay_Reason                  20000 non-null  object
dtypes: float64(1), int64(18), object(16)
memory usage: 5.3+ MB

In [6]:
df.columns

Index(['Flight_ID', 'Airline', 'Origin', 'Destination', 'Aircraft_Type',
       'Terminal', 'Gate', 'Weather_Condition', 'Flight_Date', 'Month',
       'Scheduled_Departure', 'Scheduled_Arrival', 'Status', 'Gate_Delay_Min',
       'Fuel_Delay_Min', 'Baggage_Delay_Min', 'Catering_Delay_Min',
       'Passenger_Transfer_Delay_Min', 'Cleaning_Delay_Min',
       'Security_Delay_Min', 'Maintenance_Delay_Min', 'ATC_Delay_Min',
       'Total_Delay_Min', 'Departure_Delay_Min', 'Arrival_Delay_Min',
       'Passenger_Count', 'Load_Factor (%)', 'Ground_Staff_Count',
       'Baggage_Count', 'Fuel_Quantity_Liters', 'Gate_Occupancy_Min',
       'Turnaround_Time_Min', 'Actual_Departure', 'Actual_Arrival',
       'Delay_Reason'],
      dtype='object')

In [7]:
print(df.dtypes)

Flight_ID                        object
Airline                          object
Origin                           object
Destination                      object
Aircraft_Type                    object
Terminal                         object
Gate                             object
Weather_Condition                object
Flight_Date                      object
Month                            object
Scheduled_Departure              object
Scheduled_Arrival                object
Status                           object
Gate_Delay_Min                    int64
Fuel_Delay_Min                    int64
Baggage_Delay_Min                 int64
Catering_Delay_Min                int64
Passenger_Transfer_Delay_Min      int64
Cleaning_Delay_Min                int64
Security_Delay_Min                int64
Maintenance_Delay_Min             int64
ATC_Delay_Min                     int64
Total_Delay_Min                   int64
Departure_Delay_Min               int64
Arrival_Delay_Min                 int64
Passenger_Count                   int64
Load_Factor (%)                 float64
Ground_Staff_Count                int64
Baggage_Count                     int64
Fuel_Quantity_Liters              int64
Gate_Occupancy_Min                int64
Turnaround_Time_Min               int64
Actual_Departure                 object
Actual_Arrival                   object
Delay_Reason                     object
dtype: object

In [8]:
missing_values = df.isnull().sum()
print(missing_values)

Flight_ID                         0
Airline                           0
Origin                            0
Destination                       0
Aircraft_Type                     0
Terminal                          0
Gate                              0
Weather_Condition                 0
Flight_Date                       0
Month                             0
Scheduled_Departure               0
Scheduled_Arrival                 0
Status                            0
Gate_Delay_Min                    0
Fuel_Delay_Min                    0
Baggage_Delay_Min                 0
Catering_Delay_Min                0
Passenger_Transfer_Delay_Min      0
Cleaning_Delay_Min                0
Security_Delay_Min                0
Maintenance_Delay_Min             0
ATC_Delay_Min                     0
Total_Delay_Min                   0
Departure_Delay_Min               0
Arrival_Delay_Min                 0
Passenger_Count                   0
Load_Factor (%)                   0
Ground_Staff_Count                0
Baggage_Count                     0
Fuel_Quantity_Liters              0
Gate_Occupancy_Min                0
Turnaround_Time_Min               0
Actual_Departure                999
Actual_Arrival                  999
Delay_Reason                      0
dtype: int64

In [9]:
rows_before=len(df)
df=df.drop_duplicates()
rows_after=len(df)
print("Rows before:",rows_before)
print("Rows after:",rows_after)
print("duplicates Removed:",rows_before-rows_after)

Rows before: 20000
Rows after: 20000
duplicates Removed: 0

In [10]:
numeric_cols=df.select_dtypes(include=["int64","float64"]).columns
for col in numeric_cols:
    df[col]=df[col].fillna(df[col].median())

In [11]:
categorical_cols=df.select_dtypes(include=["int64","float64"]).columns
for col in numeric_cols:
    df[col]=df[col].fillna(df[col].mode()[0])

In [12]:
df['Flight_Date ']=pd.to_datetime(df['Flight_Date'])
df.head()

,Flight_ID,Airline,Origin,Destination,Aircraft_Type,Terminal,Gate,Weather_Condition,Flight_Date,Month,...,Load_Factor (%),Ground_Staff_Count,Baggage_Count,Fuel_Quantity_Liters,Gate_Occupancy_Min,Turnaround_Time_Min,Actual_Departure,Actual_Arrival,Delay_Reason,Flight_Date
0,FL100000,Akasa Air,CCU,BOM,B777,T3,G9,Rain,2025-02-09 00:00:00,February,...,83.46,23,312,60774,53,100,2025-02-09 15:34:00,2025-02-09 17:18:00,No Delay,2025-02-09
1,FL100001,Vistara,BOM,MAA,B777,T2,G18,Clear,2025-06-17 00:00:00,June,...,95.21,22,75,30079,74,100,2025-06-17 09:15:00,2025-06-17 13:38:00,No Delay,2025-06-17
2,FL100002,Qatar Airways,MAA,CCU,B787,T1,G43,Clear,2025-04-19 00:00:00,April,...,65.68,16,191,27653,73,108,2025-04-19 10:26:00,2025-04-19 13:54:00,No Delay,2025-04-19
3,FL100003,Akasa Air,HYD,DEL,B777,T2,G24,Clear,2025-10-08 00:00:00,October,...,83.22,22,274,67394,102,105,2025-10-08 20:29:00,2025-10-08 23:29:00,No Delay,2025-10-08
4,FL100004,SpiceJet,BLR,CCU,A321,T1,G27,Clear,2025-02-25 00:00:00,February,...,94.33,8,86,63337,113,117,2025-02-25 23:21:00,2025-02-26 01:17:00,Maintenance,2025-02-25

In [13]:
df["Actual_Departure"] = pd.to_datetime(df["Actual_Departure"], errors="coerce")
df["Actual_Arrival"] = pd.to_datetime(df["Actual_Arrival"], errors="coerce")

In [14]:
df["Actual_Departure"] = df["Actual_Departure"].fillna(df["Actual_Departure"].mode()[0])

df["Actual_Arrival"] = df["Actual_Arrival"].fillna(df["Actual_Arrival"].mode()[0])

In [15]:
df["Actual_Departure"] = df["Actual_Departure"].fillna(method="ffill")

df["Actual_Arrival"] = df["Actual_Arrival"].fillna(method="ffill")

C:\Users\asus\AppData\Local\Temp\ipykernel_2328\3344216326.py:1: FutureWarning: Series.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  df["Actual_Departure"] = df["Actual_Departure"].fillna(method="ffill")
C:\Users\asus\AppData\Local\Temp\ipykernel_2328\3344216326.py:3: FutureWarning: Series.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  df["Actual_Arrival"] = df["Actual_Arrival"].fillna(method="ffill")

In [16]:
print(df[["Actual_Departure", "Actual_Arrival"]].isnull().sum())

Actual_Departure    0
Actual_Arrival      0
dtype: int64

In [17]:
df["Flight_Date"] = pd.to_datetime(df["Flight_Date"], errors="coerce")

In [18]:
df["Actual_Departure"] = pd.to_datetime(df["Actual_Departure"], errors="coerce")

In [19]:
df["Actual_Arrival"] = pd.to_datetime(df["Actual_Arrival"], errors="coerce")

In [20]:
print(df[["Flight_Date", "Actual_Departure", "Actual_Arrival"]].dtypes)

Flight_Date         datetime64[ns]
Actual_Departure    datetime64[ns]
Actual_Arrival      datetime64[ns]
dtype: object

In [21]:
missing_values = df.isnull().sum()
print(missing_values)
print(df.dtypes)

Flight_ID                       0
Airline                         0
Origin                          0
Destination                     0
Aircraft_Type                   0
Terminal                        0
Gate                            0
Weather_Condition               0
Flight_Date                     0
Month                           0
Scheduled_Departure             0
Scheduled_Arrival               0
Status                          0
Gate_Delay_Min                  0
Fuel_Delay_Min                  0
Baggage_Delay_Min               0
Catering_Delay_Min              0
Passenger_Transfer_Delay_Min    0
Cleaning_Delay_Min              0
Security_Delay_Min              0
Maintenance_Delay_Min           0
ATC_Delay_Min                   0
Total_Delay_Min                 0
Departure_Delay_Min             0
Arrival_Delay_Min               0
Passenger_Count                 0
Load_Factor (%)                 0
Ground_Staff_Count              0
Baggage_Count                   0
Fuel_Quantity_Liters            0
Gate_Occupancy_Min              0
Turnaround_Time_Min             0
Actual_Departure                0
Actual_Arrival                  0
Delay_Reason                    0
Flight_Date                     0
dtype: int64
Flight_ID                               object
Airline                                 object
Origin                                  object
Destination                             object
Aircraft_Type                           object
Terminal                                object
Gate                                    object
Weather_Condition                       object
Flight_Date                     datetime64[ns]
Month                                   object
Scheduled_Departure                     object
Scheduled_Arrival                       object
Status                                  object
Gate_Delay_Min                           int64
Fuel_Delay_Min                           int64
Baggage_Delay_Min                        int64
Catering_Delay_Min                       int64
Passenger_Transfer_Delay_Min             int64
Cleaning_Delay_Min                       int64
Security_Delay_Min                       int64
Maintenance_Delay_Min                    int64
ATC_Delay_Min                            int64
Total_Delay_Min                          int64
Departure_Delay_Min                      int64
Arrival_Delay_Min                        int64
Passenger_Count                          int64
Load_Factor (%)                        float64
Ground_Staff_Count                       int64
Baggage_Count                            int64
Fuel_Quantity_Liters                     int64
Gate_Occupancy_Min                       int64
Turnaround_Time_Min                      int64
Actual_Departure                datetime64[ns]
Actual_Arrival                  datetime64[ns]
Delay_Reason                            object
Flight_Date                     datetime64[ns]
dtype: object